edi-datawarehouse:
  outputs:
    dev:
      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      database: ${{ secrets.DEV_DATABASE }}
      password: ${{ secrets.SNOWFLAKE_PASSWORD }}
      role: ${{ secrets.SNOWFLAKE_ROLE }}
      schema: ${{ secrets.DEFAULT_SCHEMA }}
      threads: 4
      type: snowflake
      user: ${{ secrets.SNOWFLAKE_USER }}
      warehouse: ${{ secrets.DEV_WH }}
    prod:
      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      database: ${{ secrets.PROD_DATABASE }}
      password: ${{ secrets.SNOWFLAKE_PASSWORD }}
      role: ${{ secrets.SNOWFLAKE_ROLE }}
      schema: ${{ secrets.DEFAULT_SCHEMA }}
      threads: 4
      type: snowflake
      user: ${{ secrets.SNOWFLAKE_USER }}
      warehouse: ${{ secrets.PROD_WH }}
  target: prod
