name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - edi_dbt_project/**
    types: [opened, synchronize, reopened, edited]

jobs:

  references:
    name: Validate model references
    runs-on: ubuntu-latest

    env:
      # Read connection secret
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      DEV_DATABASE: ${{ secrets.DEV_DATABASE }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      DEFAULT_SCHEMA: ${{ secrets.DEFAULT_SCHEMA }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      DEV_WH: ${{ secrets.DEV_WH }}
      PROD_DATABASE: ${{ secrets.PROD_DATABASE }}
      PROD_WH: ${{ secrets.PROD_WH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake
          dbt deps --project-dir edi_dbt_project

      - name: Create manifest
        run: |
          dbt parse --project-dir edi_dbt_project --profiles-dir .dbt --target dev
      
      - name: Validate mart → base or source model rules
        run: python ci-check-model-graph.py

  dbt:
    name: DBT CI with State Comparison
    runs-on: ubuntu-latest

    env:
      # Read connection secret
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      DEV_DATABASE: ${{ secrets.DEV_DATABASE }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      DEFAULT_SCHEMA: ${{ secrets.DEFAULT_SCHEMA }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      DEV_WH: ${{ secrets.DEV_WH }}
      PROD_DATABASE: ${{ secrets.PROD_DATABASE }}
      PROD_WH: ${{ secrets.PROD_WH }}

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake
      - name: Save current branch name
        id: vars
        run: echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> "$GITHUB_OUTPUT"
      - name: Checkout main branch
        run: |
          git checkout origin/main
          dbt deps --project-dir edi_dbt_project
          dbt compile --project-dir edi_dbt_project --profiles-dir .dbt --target dev
          mkdir -p edi_dbt_project/state_artifacts
          cp edi_dbt_project/target/manifest.json edi_dbt_project/state_artifacts/manifest.json
      - name: Checkout PR branch again
        run: git checkout ${{ steps.vars.outputs.branch_name }}
      - name: Install PR dependencies & run CI tests
        run: |
          dbt deps --project-dir edi_dbt_project
          dbt compile --project-dir edi_dbt_project --profiles-dir .dbt --target dev
          dbt build --select state:modified --state edi_dbt_project/state_artifacts --project-dir edi_dbt_project --profiles-dir .dbt --target dev
